site_name: Web Dev - K33401 - Рейнгеверц В. А.
theme:
    name: material
    palette:
        scheme: slate
        primary: deep purple
        accent: deep purple
    features:
        - content.code.copy
repo_url: https://github.com/LiprikON2/ITMO_ICT_WebDevelopment_2022-2023/tree/Lr3
nav:
    - home.md
    - "Laboratory Work 1": lab1/index.ipynb
    - "Laboratory Work 2":
          - Overview: lab2/index.md
          - "Practical Work": lab2/practical.md
    - "Laboratory Work 3":
          - Overview: lab3/index.md
          - "Practical Work": lab3/practical.md
          - API:
                - "Models API": lab3/api/models.md
                - "Custom API": lab3/api/custom.md
                - "Report API": lab3/api/report.md
                - "Auth API": lab3/api/auth.md
markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
plugins:
    - mkdocs-jupyter
