site_name: Web Dev - K33401 - Рейнгеверц В. А.
theme:
    name: material
    palette:
        scheme: slate
        primary: deep purple
        accent: deep purple
    features:
        - content.code.copy
nav:
    - "Laboratory Work 3":
          - Overview: index.md
          - "Practical Work": "practical.md"
          - API:
                - "Models API": API/models.md
                - "Custom API": API/custom.md
                - "Report API": API/report.md
                - "Auth API": API/auth.md
markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
